language: node_js

node_js:
  - "10.15.3"

sudo: false

os:
  - osx
  - linux

services:
  - xvfb

cache:
  directories:
    - "node_modules"
    - ".vscode-test"

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

script:
  - npm install
  - npm run vscode:prepublish
  - npm run lint --silent
  - npm test --silent
